services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ENABLE_POSTHOG=0
      - POSTHOG_KEY=
      - POSTHOG_HOST=https://us.i.posthog.com
      - TRADYR_API_KEY=${TRADYR_API_KEY:-}
    volumes:
      - ./frontend:/app
      - /app/node_modules
