"use client";

import { useMemo, useState } from "react";
import { captureAnalytics } from "../lib/analytics";
import { arbitrageCalculation, hedgeCalculation, kellyCalculation, noVigMarket, parlayCalculation, roundRobinCalculation, settleRoundRobin, teaserCalculation } from "../lib/odds-math.mjs";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const american = (value: number | null) => value === null ? "—" : value > 0 ? `+${value}` : String(value);
const pct = (value: number) => `${(value * 100).toFixed(2)}%`;
const lineValue = (value: number) => value > 0 ? `+${value}` : String(value);

export function ParlayCalculator() {
  const [legs, setLegs] = useState([-110, 150, -125]);
  const [stake, setStake] = useState(25);
  const result = useMemo(() => parlayCalculation(legs, stake), [legs, stake]);
  const setLeg = (index: number, value: number) => { setLegs((current) => current.map((leg, legIndex) => legIndex === index ? value : leg)); captureAnalytics("parlay_calculator_changed", { input: "leg", leg_count: legs.length }); };
  return <CalculatorShell label="Build the parlay" color="#dfff4f">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{legs.map((leg, index) => <label key={index} className="font-mono text-[10px] font-black uppercase">Leg {index + 1} odds<input aria-label={`Leg ${index + 1} American odds`} type="number" value={leg} onChange={(event) => setLeg(index, Number(event.target.value))} className="mt-2 w-full border border-[#171c19] bg-white px-4 py-4 text-xl font-black outline-none focus:ring-4 focus:ring-[#8bcfff]" /></label>)}</div>
    <div className="mt-4 flex flex-wrap gap-3"><button type="button" disabled={legs.length >= 8} onClick={() => { setLegs((current) => [...current, -110]); captureAnalytics("parlay_calculator_leg_added", { leg_count: legs.length + 1 }); }} className="border border-[#171c19] bg-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">+ Add leg</button><button type="button" disabled={legs.length <= 2} onClick={() => { setLegs((current) => current.slice(0, -1)); captureAnalytics("parlay_calculator_leg_removed", { leg_count: legs.length - 1 }); }} className="border border-[#171c19] bg-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">− Remove leg</button></div>
    <MoneyInput label="Stake" value={stake} onChange={(value) => { setStake(value); captureAnalytics("parlay_calculator_changed", { input: "stake", leg_count: legs.length }); }} />
    {result ? <ResultGrid items={[{ label: "Combined odds", value: american(result.combinedAmerican) }, { label: "Implied probability", value: pct(result.impliedProbability) }, { label: "Profit", value: money.format(result.profit) }, { label: "Total payout", value: money.format(result.payout) }]} /> : <InvalidOdds />}
  </CalculatorShell>;
}

export function NoVigCalculator() {
  const [odds, setOdds] = useState([-110, -110]);
  const result = useMemo(() => noVigMarket(odds), [odds]);
  return <CalculatorShell label="Remove the vig" color="#8bcfff"><div className="grid gap-4 sm:grid-cols-2">{odds.map((value, index) => <label key={index} className="font-mono text-[10px] font-black uppercase">Side {index + 1} American odds<input aria-label={`Side ${index + 1} American odds`} type="number" value={value} onChange={(event) => { setOdds((current) => current.map((item, itemIndex) => itemIndex === index ? Number(event.target.value) : item)); captureAnalytics("no_vig_calculator_changed", { input: `side_${index + 1}` }); }} className="mt-2 w-full border border-[#171c19] bg-white px-4 py-4 text-xl font-black outline-none focus:ring-4 focus:ring-[#dfff4f]" /></label>)}</div>{result ? <ResultGrid items={[{ label: "Side 1 fair probability", value: pct(result.fairProbabilities[0]) }, { label: "Side 2 fair probability", value: pct(result.fairProbabilities[1]) }, { label: result.hold >= 0 ? "Market hold" : "Negative hold", value: pct(Math.abs(result.hold)) }]} /> : <InvalidOdds />}</CalculatorShell>;
}

export function KellyCalculator() {
  const [odds, setOdds] = useState(150); const [probability, setProbability] = useState(45); const [bankroll, setBankroll] = useState(1000); const [fraction, setFraction] = useState(0.5);
  const result = useMemo(() => kellyCalculation(odds, probability / 100, bankroll, fraction), [odds, probability, bankroll, fraction]);
  return <CalculatorShell label="Size the stake" color="#e7d7ff"><div className="grid gap-4 sm:grid-cols-3"><NumberInput label="American odds" ariaLabel="American odds" value={odds} onChange={(value) => { setOdds(value); track("kelly_calculator_changed", "odds"); }} /><NumberInput label="Your win probability (%)" ariaLabel="Estimated win probability" value={probability} min={0} max={100} onChange={(value) => { setProbability(value); track("kelly_calculator_changed", "probability"); }} /><MoneyInput label="Bankroll" value={bankroll} compact onChange={(value) => { setBankroll(value); track("kelly_calculator_changed", "bankroll"); }} /></div><label className="mt-5 block font-mono text-[10px] font-black uppercase">Kelly fraction<select aria-label="Kelly fraction" value={fraction} onChange={(event) => { setFraction(Number(event.target.value)); track("kelly_calculator_changed", "fraction"); }} className="mt-2 w-full border border-[#171c19] bg-white px-4 py-4 text-base font-black outline-none focus:ring-4 focus:ring-[#dfff4f]"><option value={1}>Full Kelly</option><option value={0.5}>Half Kelly</option><option value={0.25}>Quarter Kelly</option></select></label>{result ? <><ResultGrid items={[{ label: "Full Kelly", value: pct(result.fullKelly) }, { label: "Selected fraction", value: pct(result.selectedKelly) }, { label: "Calculated stake", value: money.format(result.stake) }, { label: "Expected return per $1", value: `${result.expectedReturn >= 0 ? "+" : ""}${(result.expectedReturn * 100).toFixed(2)}¢` }]} /><p className="mt-4 text-xs leading-6 text-[#59605c]">A $0 result means your probability estimate does not show a positive mathematical edge at these odds.</p></> : <InvalidOdds />}</CalculatorShell>;
}

export function HedgeCalculator() {
  const [initialOdds, setInitialOdds] = useState(200); const [initialStake, setInitialStake] = useState(100); const [hedgeOdds, setHedgeOdds] = useState(-110);
  const result = useMemo(() => hedgeCalculation(initialOdds, initialStake, hedgeOdds), [initialOdds, initialStake, hedgeOdds]);
  return <CalculatorShell label="Balance both outcomes" color="#ffb29a"><div className="grid gap-4 sm:grid-cols-3"><NumberInput label="Original bet odds" ariaLabel="Original bet American odds" value={initialOdds} onChange={(value) => { setInitialOdds(value); track("hedge_calculator_changed", "initial_odds"); }} /><MoneyInput label="Original stake" value={initialStake} compact onChange={(value) => { setInitialStake(value); track("hedge_calculator_changed", "initial_stake"); }} /><NumberInput label="Hedge odds" ariaLabel="Hedge American odds" value={hedgeOdds} onChange={(value) => { setHedgeOdds(value); track("hedge_calculator_changed", "hedge_odds"); }} /></div>{result ? <ResultGrid items={[{ label: "Hedge stake", value: money.format(result.hedgeStake) }, { label: "Profit either way", value: money.format(result.equalizedProfit) }, { label: "Total staked", value: money.format(result.totalStaked) }, { label: "Return on winner", value: money.format(result.lockedReturn) }]} /> : <InvalidOdds />}</CalculatorShell>;
}

export function RoundRobinCalculator() {
  const [legs, setLegs] = useState([-110, 120, -105, 150]);
  const [statuses, setStatuses] = useState<Array<"pending" | "win" | "loss" | "push">>(["pending", "pending", "pending", "pending"]);
  const [combinationSize, setCombinationSize] = useState(2);
  const [stakePerBet, setStakePerBet] = useState(5);
  const result = useMemo(() => roundRobinCalculation(legs, combinationSize, stakePerBet), [legs, combinationSize, stakePerBet]);
  const settlement = useMemo(() => settleRoundRobin(legs, statuses, combinationSize, stakePerBet), [legs, statuses, combinationSize, stakePerBet]);
  const resize = (next: number[]) => { setLegs(next); setStatuses((current) => next.length > current.length ? [...current, "pending"] : current.slice(0, next.length)); if (combinationSize >= next.length) setCombinationSize(next.length - 1); };
  return <CalculatorShell label="Build every combination" color="#dfff4f">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{legs.map((leg, index) => <div key={index} className="border border-[#171c19] bg-white p-3"><NumberInput label={`Leg ${index + 1} odds`} ariaLabel={`Round robin leg ${index + 1} American odds`} value={leg} onChange={(value) => { setLegs((current) => current.map((item, itemIndex) => itemIndex === index ? value : item)); trackCount("round_robin_calculator_changed", "leg", "leg_count", legs.length); }} /><label className="mt-3 block font-mono text-[10px] font-black uppercase">Result<select aria-label={`Round robin leg ${index + 1} result`} value={statuses[index]} onChange={(event) => { setStatuses((current) => current.map((status, statusIndex) => statusIndex === index ? event.target.value as "pending" | "win" | "loss" | "push" : status)); trackCount("round_robin_calculator_changed", "result", "leg_count", legs.length); }} className="mt-2 w-full border border-[#171c19] bg-[#f4f1e8] px-3 py-3 text-sm font-black outline-none focus:ring-4 focus:ring-[#8bcfff]"><option value="pending">Not final</option><option value="win">Win</option><option value="loss">Loss</option><option value="push">Push</option></select></label></div>)}</div>
    <div className="mt-4 flex flex-wrap gap-3"><button type="button" disabled={legs.length >= 8} onClick={() => { resize([...legs, -110]); trackCount("round_robin_leg_added", "add", "leg_count", legs.length + 1); }} className="border border-[#171c19] bg-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">+ Add leg</button><button type="button" disabled={legs.length <= 3} onClick={() => { resize(legs.slice(0, -1)); trackCount("round_robin_leg_removed", "remove", "leg_count", legs.length - 1); }} className="border border-[#171c19] bg-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">− Remove leg</button></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="font-mono text-[10px] font-black uppercase">Parlay size<select aria-label="Round robin parlay size" value={combinationSize} onChange={(event) => { setCombinationSize(Number(event.target.value)); track("round_robin_calculator_changed", "combination_size"); }} className="mt-2 w-full border border-[#171c19] bg-white px-4 py-4 text-base font-black outline-none focus:ring-4 focus:ring-[#8bcfff]">{Array.from({ length: legs.length - 2 }, (_, index) => index + 2).map((size) => <option key={size} value={size}>{size}-leg combinations</option>)}</select></label><MoneyInput label="Stake per bet" value={stakePerBet} compact onChange={(value) => { setStakePerBet(value); track("round_robin_calculator_changed", "stake_per_bet"); }} /></div>
    {result && settlement ? <><ResultGrid items={[{ label: "Separate bets", value: String(result.betCount) }, { label: "Total stake", value: money.format(result.totalStake) }, { label: "Max profit", value: money.format(result.maxProfit) }, { label: "Max payout", value: money.format(result.maxPayout) }]} /><p className="mt-4 text-xs leading-6 text-[#59605c]">Maximum payout assumes every leg wins. A winning ticket requires at least {result.minimumWinningLegs} correct legs in the same combination.</p><div className="mt-7 border-t border-[#171c19] pt-6"><span className="eyebrow bg-white">Settle the card</span><p className="mt-4 text-sm font-bold leading-6">Mark each leg above as a win, loss or push to calculate the surviving tickets and final return.</p><ResultGrid items={[{ label: "Winning bets", value: String(settlement.winningBets) }, { label: "Lost bets", value: String(settlement.lostBets) }, { label: "Push-only bets", value: String(settlement.pushBets) }, { label: "Unresolved bets", value: String(settlement.pendingBets) }, { label: "Payout so far", value: money.format(settlement.settledPayout) }, { label: "Final net result", value: settlement.netResult === null ? "Finish grading" : money.format(settlement.netResult) }]} /></div></> : <InvalidOdds />}
  </CalculatorShell>;
}

export function ArbitrageCalculator() {
  const [outcomes, setOutcomes] = useState([110, 110]);
  const [basis, setBasis] = useState<"stake" | "return">("stake");
  const [amount, setAmount] = useState(100);
  const result = useMemo(() => arbitrageCalculation(outcomes, amount, basis), [outcomes, amount, basis]);
  return <CalculatorShell label="Balance every outcome" color="#8bcfff">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{outcomes.map((value, index) => <NumberInput key={index} label={`Outcome ${index + 1} odds`} ariaLabel={`Arbitrage outcome ${index + 1} American odds`} value={value} onChange={(next) => { setOutcomes((current) => current.map((item, itemIndex) => itemIndex === index ? next : item)); trackCount("arbitrage_calculator_changed", "outcome", "outcome_count", outcomes.length); }} />)}</div>
    <div className="mt-4 flex flex-wrap gap-3"><button type="button" disabled={outcomes.length >= 6} onClick={() => { setOutcomes((current) => [...current, 200]); trackCount("arbitrage_outcome_added", "add", "outcome_count", outcomes.length + 1); }} className="border border-[#171c19] bg-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">+ Add outcome</button><button type="button" disabled={outcomes.length <= 2} onClick={() => { setOutcomes((current) => current.slice(0, -1)); trackCount("arbitrage_outcome_removed", "remove", "outcome_count", outcomes.length - 1); }} className="border border-[#171c19] bg-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">− Remove outcome</button></div>
    <div className="mt-5 grid grid-cols-2 gap-px border border-[#171c19] bg-[#171c19]" aria-label="Allocation basis"><button type="button" aria-pressed={basis === "stake"} onClick={() => { setBasis("stake"); track("arbitrage_calculator_changed", "basis"); }} className={`px-3 py-3 font-mono text-[10px] font-black uppercase ${basis === "stake" ? "bg-[#dfff4f]" : "bg-white"}`}>Split a total stake</button><button type="button" aria-pressed={basis === "return"} onClick={() => { setBasis("return"); track("arbitrage_calculator_changed", "basis"); }} className={`px-3 py-3 font-mono text-[10px] font-black uppercase ${basis === "return" ? "bg-[#dfff4f]" : "bg-white"}`}>Target an equal return</button></div>
    <MoneyInput label={basis === "stake" ? "Total stake" : "Desired equal return"} value={amount} onChange={(value) => { setAmount(value); track("arbitrage_calculator_changed", "amount"); }} />
    {result ? <><div className={`mt-7 border border-[#171c19] p-4 font-black ${result.isArbitrage ? "bg-[#dfff4f]" : "bg-white"}`}>{result.isArbitrage ? "These entered prices form a mathematical arbitrage." : "These entered prices do not form a mathematical arbitrage."}</div><ResultGrid items={[{ label: "Implied probability total", value: pct(result.impliedTotal) }, { label: "Total stake", value: money.format(result.totalStake) }, { label: "Equal return", value: money.format(result.lockedReturn) }, { label: "Result after stakes", value: money.format(result.lockedProfit) }, { label: "Return on stake", value: pct(result.roi) }]} /><div className="mt-5 grid gap-px border border-[#171c19] bg-[#171c19] sm:grid-cols-2 lg:grid-cols-3">{result.stakes.map((stake, index) => <div key={index} className="bg-white p-4"><span className="font-mono text-[9px] font-black uppercase text-[#59605c]">Outcome {index + 1} stake</span><strong className="mt-2 block text-2xl">{money.format(stake)}</strong></div>)}</div></> : <InvalidOdds />}
  </CalculatorShell>;
}

export function TeaserCalculator() {
  const [legs, setLegs] = useState<Array<{ type: "spread" | "over" | "under"; line: number }>>([{ type: "spread", line: -7.5 }, { type: "spread", line: 2.5 }]);
  const [points, setPoints] = useState(6);
  const [odds, setOdds] = useState(-120);
  const [stake, setStake] = useState(25);
  const result = useMemo(() => teaserCalculation(legs, points, odds, stake), [legs, points, odds, stake]);
  const setLeg = (index: number, update: Partial<{ type: "spread" | "over" | "under"; line: number }>) => setLegs((current) => current.map((leg, legIndex) => legIndex === index ? { ...leg, ...update } : leg));
  return <CalculatorShell label="Move the lines" color="#e7d7ff">
    <div className="space-y-3">{legs.map((leg, index) => <div key={index} className="grid gap-3 sm:grid-cols-2"><label className="font-mono text-[10px] font-black uppercase">Leg {index + 1} market<select aria-label={`Teaser leg ${index + 1} market`} value={leg.type} onChange={(event) => { setLeg(index, { type: event.target.value as "spread" | "over" | "under" }); trackCount("teaser_calculator_changed", "market", "leg_count", legs.length); }} className="mt-2 w-full border border-[#171c19] bg-white px-4 py-4 text-base font-black outline-none focus:ring-4 focus:ring-[#dfff4f]"><option value="spread">Team spread</option><option value="over">Over total</option><option value="under">Under total</option></select></label><NumberInput label="Original line" ariaLabel={`Teaser leg ${index + 1} original line`} value={leg.line} onChange={(value) => { setLeg(index, { line: value }); trackCount("teaser_calculator_changed", "line", "leg_count", legs.length); }} /></div>)}</div>
    <div className="mt-4 flex flex-wrap gap-3"><button type="button" disabled={legs.length >= 6} onClick={() => { setLegs((current) => [...current, { type: "spread", line: -3.5 }]); trackCount("teaser_leg_added", "add", "leg_count", legs.length + 1); }} className="border border-[#171c19] bg-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">+ Add leg</button><button type="button" disabled={legs.length <= 2} onClick={() => { setLegs((current) => current.slice(0, -1)); trackCount("teaser_leg_removed", "remove", "leg_count", legs.length - 1); }} className="border border-[#171c19] bg-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">− Remove leg</button></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-3"><NumberInput label="Teaser points" ariaLabel="Teaser points" value={points} min={0.5} onChange={(value) => { setPoints(value); track("teaser_calculator_changed", "points"); }} /><NumberInput label="Teaser odds" ariaLabel="Teaser American odds" value={odds} onChange={(value) => { setOdds(value); track("teaser_calculator_changed", "odds"); }} /><MoneyInput label="Stake" value={stake} compact onChange={(value) => { setStake(value); track("teaser_calculator_changed", "stake"); }} /></div>
    {result ? <><div className="mt-7 grid gap-px border border-[#171c19] bg-[#171c19] sm:grid-cols-2 lg:grid-cols-3">{result.adjustedLines.map((line, index) => <div key={index} className="bg-white p-4"><span className="font-mono text-[9px] font-black uppercase text-[#59605c]">Leg {index + 1} adjusted line</span><strong className="mt-2 block text-2xl">{legs[index].type === "spread" ? lineValue(line) : `${legs[index].type === "over" ? "Over" : "Under"} ${line}`}</strong></div>)}</div><ResultGrid items={[{ label: "Teaser odds", value: american(odds) }, { label: "Profit if all legs win", value: money.format(result.profit) }, { label: "Total payout", value: money.format(result.payout) }]} /></> : <InvalidOdds />}
  </CalculatorShell>;
}

function CalculatorShell({ label, color, children }: { label: string; color: string; children: React.ReactNode }) { return <section className="border border-[#171c19] p-6 shadow-[6px_6px_0_#171c19] sm:p-8" style={{ backgroundColor: color }}><span className="eyebrow bg-white">{label}</span><div className="mt-7">{children}</div></section>; }
function NumberInput({ label, ariaLabel, value, onChange, min, max }: { label: string; ariaLabel: string; value: number; onChange: (value: number) => void; min?: number; max?: number }) { return <label className="font-mono text-[10px] font-black uppercase">{label}<input aria-label={ariaLabel} type="number" value={value} min={min} max={max} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 w-full border border-[#171c19] bg-white px-4 py-4 text-xl font-black outline-none focus:ring-4 focus:ring-[#dfff4f]" /></label>; }
function MoneyInput({ label, value, onChange, compact = false }: { label: string; value: number; onChange: (value: number) => void; compact?: boolean }) { return <label className={`${compact ? "" : "mt-5 block max-w-sm"} font-mono text-[10px] font-black uppercase`}>{label}<div className="mt-2 flex border border-[#171c19] bg-white focus-within:ring-4 focus-within:ring-[#8bcfff]"><span className="px-4 py-4 text-xl font-black">$</span><input aria-label={label} type="number" min="0" value={value} onChange={(event) => onChange(Number(event.target.value))} className="min-w-0 flex-1 bg-transparent py-4 pr-4 text-xl font-black outline-none" /></div></label>; }
function ResultGrid({ items }: { items: Array<{ label: string; value: string }> }) { return <div className="mt-7 grid gap-px border border-[#171c19] bg-[#171c19] sm:grid-cols-2 lg:grid-cols-4">{items.map((item) => <div key={item.label} className="bg-white p-4"><span className="font-mono text-[9px] font-black uppercase text-[#59605c]">{item.label}</span><strong className="mt-2 block text-2xl tracking-[-0.04em]">{item.value}</strong></div>)}</div>; }
function InvalidOdds() { return <p className="mt-6 border border-[#b23a1b] bg-white p-4 text-sm font-black">Use valid American odds of +100 or higher, or −100 or lower.</p>; }
function track(event: string, input: string) { captureAnalytics(event, { input }); }
function trackCount(event: string, input: string, countName: "leg_count" | "outcome_count", count: number) { captureAnalytics(event, { input, [countName]: count }); }
