"use client";

import { useMemo, useState } from "react";
import { captureAnalytics } from "../lib/analytics";
import { hedgeCalculation, kellyCalculation, noVigMarket, parlayCalculation } from "../lib/odds-math.mjs";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const american = (value: number | null) => value === null ? "—" : value > 0 ? `+${value}` : String(value);
const pct = (value: number) => `${(value * 100).toFixed(2)}%`;

export function ParlayCalculator() {
  const [legs, setLegs] = useState([-110, 150, -125]);
  const [stake, setStake] = useState(25);
  const result = useMemo(() => parlayCalculation(legs, stake), [legs, stake]);
  const setLeg = (index: number, value: number) => { setLegs((current) => current.map((leg, legIndex) => legIndex === index ? value : leg)); captureAnalytics("parlay_calculator_changed", { input: "leg", leg_count: legs.length }); };
  return <CalculatorShell label="Build the parlay" color="#dfff4f">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{legs.map((leg, index) => <label key={index} className="font-mono text-[10px] font-black uppercase">Leg {index + 1} odds<input aria-label={`Leg ${index + 1} American odds`} type="number" value={leg} onChange={(event) => setLeg(index, Number(event.target.value))} className="mt-2 w-full border border-[#171c19] bg-white px-4 py-4 text-xl font-black outline-none focus:ring-4 focus:ring-[#8bcfff]" /></label>)}</div>
    <div className="mt-4 flex flex-wrap gap-3"><button type="button" disabled={legs.length >= 8} onClick={() => { setLegs((current) => [...current, -110]); captureAnalytics("parlay_calculator_leg_added", { leg_count: legs.length + 1 }); }} className="border border-[#171c19] bg-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">+ Add leg</button><button type="button" disabled={legs.length <= 2} onClick={() => { setLegs((current) => current.slice(0, -1)); captureAnalytics("parlay_calculator_leg_removed", { leg_count: legs.length - 1 }); }} className="border border-[#171c19] bg-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">− Remove leg</button></div>
    <MoneyInput label="Stake" value={stake} onChange={(value) => { setStake(value); captureAnalytics("parlay_calculator_changed", { input: "stake", leg_count: legs.length }); }} />
    {result ? <ResultGrid items={[{ label: "Combined odds", value: american(result.combinedAmerican) }, { label: "Implied probability", value: pct(result.impliedProbability) }, { label: "Profit", value: money.format(result.profit) }, { label: "Total payout", value: money.format(result.payout) }]} /> : <InvalidOdds />}
  </CalculatorShell>;
}

export function NoVigCalculator() {
  const [odds, setOdds] = useState([-110, -110]);
  const result = useMemo(() => noVigMarket(odds), [odds]);
  return <CalculatorShell label="Remove the vig" color="#8bcfff"><div className="grid gap-4 sm:grid-cols-2">{odds.map((value, index) => <label key={index} className="font-mono text-[10px] font-black uppercase">Side {index + 1} American odds<input aria-label={`Side ${index + 1} American odds`} type="number" value={value} onChange={(event) => { setOdds((current) => current.map((item, itemIndex) => itemIndex === index ? Number(event.target.value) : item)); captureAnalytics("no_vig_calculator_changed", { input: `side_${index + 1}` }); }} className="mt-2 w-full border border-[#171c19] bg-white px-4 py-4 text-xl font-black outline-none focus:ring-4 focus:ring-[#dfff4f]" /></label>)}</div>{result ? <ResultGrid items={[{ label: "Side 1 fair probability", value: pct(result.fairProbabilities[0]) }, { label: "Side 2 fair probability", value: pct(result.fairProbabilities[1]) }, { label: result.hold >= 0 ? "Market hold" : "Negative hold", value: pct(Math.abs(result.hold)) }]} /> : <InvalidOdds />}</CalculatorShell>;
}

export function KellyCalculator() {
  const [odds, setOdds] = useState(150); const [probability, setProbability] = useState(45); const [bankroll, setBankroll] = useState(1000); const [fraction, setFraction] = useState(0.5);
  const result = useMemo(() => kellyCalculation(odds, probability / 100, bankroll, fraction), [odds, probability, bankroll, fraction]);
  return <CalculatorShell label="Size the stake" color="#e7d7ff"><div className="grid gap-4 sm:grid-cols-3"><NumberInput label="American odds" ariaLabel="American odds" value={odds} onChange={(value) => { setOdds(value); track("kelly_calculator_changed", "odds"); }} /><NumberInput label="Your win probability (%)" ariaLabel="Estimated win probability" value={probability} min={0} max={100} onChange={(value) => { setProbability(value); track("kelly_calculator_changed", "probability"); }} /><MoneyInput label="Bankroll" value={bankroll} compact onChange={(value) => { setBankroll(value); track("kelly_calculator_changed", "bankroll"); }} /></div><label className="mt-5 block font-mono text-[10px] font-black uppercase">Kelly fraction<select aria-label="Kelly fraction" value={fraction} onChange={(event) => { setFraction(Number(event.target.value)); track("kelly_calculator_changed", "fraction"); }} className="mt-2 w-full border border-[#171c19] bg-white px-4 py-4 text-base font-black outline-none focus:ring-4 focus:ring-[#dfff4f]"><option value={1}>Full Kelly</option><option value={0.5}>Half Kelly</option><option value={0.25}>Quarter Kelly</option></select></label>{result ? <><ResultGrid items={[{ label: "Full Kelly", value: pct(result.fullKelly) }, { label: "Selected fraction", value: pct(result.selectedKelly) }, { label: "Calculated stake", value: money.format(result.stake) }, { label: "Expected return per $1", value: `${result.expectedReturn >= 0 ? "+" : ""}${(result.expectedReturn * 100).toFixed(2)}¢` }]} /><p className="mt-4 text-xs leading-6 text-[#59605c]">A $0 result means your probability estimate does not show a positive mathematical edge at these odds.</p></> : <InvalidOdds />}</CalculatorShell>;
}

export function HedgeCalculator() {
  const [initialOdds, setInitialOdds] = useState(200); const [initialStake, setInitialStake] = useState(100); const [hedgeOdds, setHedgeOdds] = useState(-110);
  const result = useMemo(() => hedgeCalculation(initialOdds, initialStake, hedgeOdds), [initialOdds, initialStake, hedgeOdds]);
  return <CalculatorShell label="Balance both outcomes" color="#ffb29a"><div className="grid gap-4 sm:grid-cols-3"><NumberInput label="Original bet odds" ariaLabel="Original bet American odds" value={initialOdds} onChange={(value) => { setInitialOdds(value); track("hedge_calculator_changed", "initial_odds"); }} /><MoneyInput label="Original stake" value={initialStake} compact onChange={(value) => { setInitialStake(value); track("hedge_calculator_changed", "initial_stake"); }} /><NumberInput label="Hedge odds" ariaLabel="Hedge American odds" value={hedgeOdds} onChange={(value) => { setHedgeOdds(value); track("hedge_calculator_changed", "hedge_odds"); }} /></div>{result ? <ResultGrid items={[{ label: "Hedge stake", value: money.format(result.hedgeStake) }, { label: "Profit either way", value: money.format(result.equalizedProfit) }, { label: "Total staked", value: money.format(result.totalStaked) }, { label: "Return on winner", value: money.format(result.lockedReturn) }]} /> : <InvalidOdds />}</CalculatorShell>;
}

function CalculatorShell({ label, color, children }: { label: string; color: string; children: React.ReactNode }) { return <section className="border border-[#171c19] p-6 shadow-[6px_6px_0_#171c19] sm:p-8" style={{ backgroundColor: color }}><span className="eyebrow bg-white">{label}</span><div className="mt-7">{children}</div></section>; }
function NumberInput({ label, ariaLabel, value, onChange, min, max }: { label: string; ariaLabel: string; value: number; onChange: (value: number) => void; min?: number; max?: number }) { return <label className="font-mono text-[10px] font-black uppercase">{label}<input aria-label={ariaLabel} type="number" value={value} min={min} max={max} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 w-full border border-[#171c19] bg-white px-4 py-4 text-xl font-black outline-none focus:ring-4 focus:ring-[#dfff4f]" /></label>; }
function MoneyInput({ label, value, onChange, compact = false }: { label: string; value: number; onChange: (value: number) => void; compact?: boolean }) { return <label className={`${compact ? "" : "mt-5 block max-w-sm"} font-mono text-[10px] font-black uppercase`}>{label}<div className="mt-2 flex border border-[#171c19] bg-white focus-within:ring-4 focus-within:ring-[#8bcfff]"><span className="px-4 py-4 text-xl font-black">$</span><input aria-label={label} type="number" min="0" value={value} onChange={(event) => onChange(Number(event.target.value))} className="min-w-0 flex-1 bg-transparent py-4 pr-4 text-xl font-black outline-none" /></div></label>; }
function ResultGrid({ items }: { items: Array<{ label: string; value: string }> }) { return <div className="mt-7 grid gap-px border border-[#171c19] bg-[#171c19] sm:grid-cols-2 lg:grid-cols-4">{items.map((item) => <div key={item.label} className="bg-white p-4"><span className="font-mono text-[9px] font-black uppercase text-[#59605c]">{item.label}</span><strong className="mt-2 block text-2xl tracking-[-0.04em]">{item.value}</strong></div>)}</div>; }
function InvalidOdds() { return <p className="mt-6 border border-[#b23a1b] bg-white p-4 text-sm font-black">Use valid American odds of +100 or higher, or −100 or lower.</p>; }
function track(event: string, input: string) { captureAnalytics(event, { input }); }
