import Link from "next/link";
import AnalyticsPageView from "./AnalyticsPageView";
import BettingDisclosure from "./BettingDisclosure";
import JsonLd from "./JsonLd";
import TeamLogo from "./TeamLogo";
import { atsLean, atsWeekPath, formatAmericanOdds, formatProbability, formatSpread, gameResult, getPredictionGamesForWeek, moneylinePick, predictionGamePath, predictionHubPath, predictionRelease, predictionUpdatedAt, predictionValidation, predictionWeekPath, projectedScore, totalLean, totalsWeekPath, winner } from "../lib/nfl-predictions";
import { formatGameDate, formatGameTime } from "../lib/team-data";

const SITE_URL = "https://fantasytradetarget.com";
type Mode = "all" | "ats" | "totals";

export default function NflPredictionWeekPage({ week, mode }: { week: number; mode: Mode }) {
  const games = getPredictionGamesForWeek(week);
  const upcoming = games.filter((game) => game.snapshot.status === "pregame");
  const path = mode === "ats" ? atsWeekPath(week) : mode === "totals" ? totalsWeekPath(week) : predictionWeekPath(week);
  const title = mode === "ats" ? `NFL Week ${week} Picks Against the Spread` : mode === "totals" ? `NFL Week ${week} Over/Under Picks` : `NFL Week ${week} Picks and Predictions`;
  const ordered = [...games].sort((left, right) => mode === "ats" ? (right.snapshot.spreadEdge === null || right.snapshot.spreadEdge === undefined ? -1 : Math.abs(right.snapshot.spreadEdge)) - (left.snapshot.spreadEdge === null || left.snapshot.spreadEdge === undefined ? -1 : Math.abs(left.snapshot.spreadEdge)) : mode === "totals" ? (right.snapshot.totalEdge === null || right.snapshot.totalEdge === undefined ? -1 : Math.abs(right.snapshot.totalEdge)) - (left.snapshot.totalEdge === null || left.snapshot.totalEdge === undefined ? -1 : Math.abs(left.snapshot.totalEdge)) : 0);
  const updated = formatUpdated(predictionUpdatedAt());
  const faqs = buildFaqs(week, mode);
  const eventName = mode === "ats" ? "nfl_ats_picks_viewed" : mode === "totals" ? "nfl_totals_picks_viewed" : "nfl_prediction_week_viewed";

  return <>
    <AnalyticsPageView eventName={eventName} properties={{ week, game_count: games.length, pregame_count: upcoming.length, release_id: predictionRelease.releaseId }} />
    <JsonLd data={buildSchema(path, title, week, ordered, faqs)} />
    <nav className="page-wrap flex flex-wrap gap-2 py-4 font-mono text-[10px] font-bold uppercase tracking-[0.08em] text-[#69706c]" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href={predictionHubPath()}>NFL picks</Link><span>/</span><span className="text-[#171c19]">Week {week}{mode === "ats" ? " ATS" : mode === "totals" ? " totals" : ""}</span></nav>
    <section className="border-y border-[#171c19] bg-[#ffb29a]"><div className="page-wrap py-14 sm:py-20"><span className="eyebrow bg-white">2026 NFL · market snapshot {updated}</span><h1 className="mt-7 max-w-6xl text-[clamp(3rem,7vw,6.8rem)] font-black uppercase leading-[0.84] tracking-[-0.075em]">{title}<span className="text-[#8c2f14]">.</span></h1><p className="mt-8 max-w-4xl border-l-4 border-[#171c19] pl-5 text-lg font-black leading-8">{heroAnswer(upcoming, mode)} Every number below is tied to the displayed market snapshot and a pregame model run.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={predictionWeekPath(week)} className={tabClass(mode === "all")}>All predictions</Link><Link href={atsWeekPath(week)} className={tabClass(mode === "ats")}>Against the spread</Link><Link href={totalsWeekPath(week)} className={tabClass(mode === "totals")}>Over / under</Link></div></div></section>
    <section className="page-wrap py-12"><div className="mb-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Games on the slate" value={String(games.length)} /><Metric label={`${predictionValidation.season} straight up`} value={`${Math.round(predictionValidation.straightUp.accuracy * 1000) / 10}%`} /><Metric label={`${predictionValidation.season} ATS`} value={`${predictionValidation.againstSpread.wins}–${predictionValidation.againstSpread.losses}`} /><Metric label={`${predictionValidation.season} totals`} value={`${predictionValidation.totals.wins}–${predictionValidation.totals.losses}`} /></div><div className="grid gap-5 xl:grid-cols-2">{ordered.map((game) => <GameCard key={game.snapshot.gameId} game={game} mode={mode} />)}</div></section>
    <section className="border-y border-[#171c19] bg-[#dfff4f]"><div className="page-wrap grid gap-8 py-12 lg:grid-cols-2"><div><span className="eyebrow bg-white">Read the number</span><h2 className="section-title mt-6">A model difference, not a promise.</h2></div><div className="space-y-4 text-sm leading-7"><p>FTT blends opponent-adjusted scoring margin, recent scoring, prior-season strength, site and rest. The market line is a separate input used only to calculate the displayed difference.</p><p>The same rules went {predictionValidation.straightUp.correct}–{predictionValidation.straightUp.graded - predictionValidation.straightUp.correct} straight up, {predictionValidation.againstSpread.wins}–{predictionValidation.againstSpread.losses} ATS and {predictionValidation.totals.wins}–{predictionValidation.totals.losses} on totals across {predictionValidation.games} games in the {predictionValidation.season} Weeks {predictionValidation.weeks} walk-forward. The ATS and totals records were effectively coin flips; the displayed differences are research signals, not a proven wagering edge.</p><Link href="/methodology#nfl-predictions" className="inline-block font-mono text-[10px] font-black uppercase underline">See the complete methodology →</Link></div></div></section>
    <section className="page-wrap py-12"><span className="eyebrow">Questions, answered</span><div className="mt-7 grid gap-px border border-[#171c19] bg-[#171c19] lg:grid-cols-2">{faqs.map(({ question, answer }) => <article key={question} className="bg-[#f3f0e7] p-6"><h2 className="text-xl font-black tracking-[-0.03em]">{question}</h2><p className="mt-3 text-sm leading-7 text-[#69706c]">{answer}</p></article>)}</div></section>
    <BettingDisclosure />
  </>;
}

function GameCard({ game, mode }: { game: ReturnType<typeof getPredictionGamesForWeek>[number]; mode: Mode }) {
  const picked = winner(game);
  const score = projectedScore(game);
  const moneyline = moneylinePick(game);
  const spread = atsLean(game);
  const total = totalLean(game);
  const result = gameResult(game);
  return <article className="border border-[#171c19] bg-white p-6 shadow-[5px_5px_0_#171c19]"><div className="flex items-center justify-between gap-4"><TeamSide team={game.away} label="Away" /><span className="font-mono text-xs font-black">AT</span><TeamSide team={game.home} label="Home" reverse /></div><div className="mt-6 border-y border-[#bcb9ae] py-4"><span className="font-mono text-[10px] font-bold uppercase text-[#69706c]">{game.homeGame.weekday} · {formatGameDate(game.homeGame.date)} · {formatGameTime(game.homeGame.time)}</span>{result ? <p className="mt-2 text-2xl font-black">Final: {game.away.nickname} {result.away}, {game.home.nickname} {result.home}</p> : <p className="mt-2 text-2xl font-black">{picked?.name ?? "No archived pregame pick"} {score ? `${score.away}–${score.home}` : ""}</p>}</div>{game.snapshot.status === "pregame" ? <div className="mt-5 grid grid-cols-3 gap-px border border-[#171c19] bg-[#171c19] text-center"><PickMetric label="Win pick" value={moneyline ? `${moneyline.team.nickname} ${formatProbability(moneyline.probability)}` : "—"} active={mode === "all"} /><PickMetric label="ATS lean" value={spread ? spread.pass ? "Pass" : `${spread.team.abbr} ${formatSpread(spread.line)}` : "—"} active={mode === "ats"} /><PickMetric label="Total lean" value={total ? total.pass ? "Pass" : `${total.side} ${total.line}` : "—"} active={mode === "totals"} /></div> : <p className="mt-5 border border-[#171c19] bg-[#e4dfd2] p-4 text-sm leading-6">This game started before FTT&apos;s first prediction snapshot, so the page shows market context and the result when available without inventing a pregame pick.</p>}<div className="mt-5 flex items-end justify-between gap-4"><p className="text-xs leading-5 text-[#69706c]">Market: {game.away.abbr} {formatAmericanOdds(game.snapshot.market.awayMoneyline)} · {game.home.abbr} {formatAmericanOdds(game.snapshot.market.homeMoneyline)} · total {game.snapshot.market.totalLine ?? "—"}</p><Link href={predictionGamePath(game.snapshot.week, game.slug)} className="shrink-0 font-mono text-[10px] font-black uppercase underline">Full game file →</Link></div></article>;
}

function TeamSide({ team, label, reverse = false }: { team: ReturnType<typeof getPredictionGamesForWeek>[number]["home"]; label: string; reverse?: boolean }) { return <div className={`flex items-center gap-3 ${reverse ? "flex-row-reverse text-right" : ""}`}><TeamLogo team={team.abbr} size={48} decorative /><div><span className="font-mono text-[9px] font-bold uppercase text-[#69706c]">{label}</span><strong className="block text-lg leading-tight">{team.nickname}</strong></div></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <dl className="border border-[#171c19] bg-[#f3f0e7] p-5"><dt className="font-mono text-[9px] font-black uppercase text-[#69706c]">{label}</dt><dd className="mt-3 text-2xl font-black tracking-[-0.04em]">{value}</dd></dl>; }
function PickMetric({ label, value, active }: { label: string; value: string; active: boolean }) { return <dl className={`p-3 ${active ? "bg-[#dfff4f]" : "bg-[#f3f0e7]"}`}><dt className="font-mono text-[8px] font-black uppercase text-[#69706c]">{label}</dt><dd className="mt-2 text-sm font-black">{value}</dd></dl>; }
function tabClass(active: boolean) { return `border border-[#171c19] px-5 py-4 font-mono text-[10px] font-black uppercase shadow-[3px_3px_0_#171c19] ${active ? "bg-[#171c19] text-white" : "bg-white"}`; }
function formatUpdated(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit", timeZone: "America/New_York", timeZoneName: "short" }).format(new Date(value)); }
function heroAnswer(games: ReturnType<typeof getPredictionGamesForWeek>, mode: Mode) { const ranked = [...games].filter((game) => game.snapshot.status === "pregame").sort((left, right) => mode === "ats" ? Math.abs(right.snapshot.spreadEdge ?? 0) - Math.abs(left.snapshot.spreadEdge ?? 0) : mode === "totals" ? Math.abs(right.snapshot.totalEdge ?? 0) - Math.abs(left.snapshot.totalEdge ?? 0) : Math.abs((right.snapshot.homeWinProbability ?? 0.5) - 0.5) - Math.abs((left.snapshot.homeWinProbability ?? 0.5) - 0.5)); const game = ranked[0]; if (!game) return "The current slate is complete."; if (mode === "ats") { const lean = atsLean(game); return lean ? `${lean.team.name} has the largest current model-to-spread difference.` : "Compare every spread with the FTT number."; } if (mode === "totals") { const lean = totalLean(game); return lean ? `${game.away.nickname}–${game.home.nickname} has the largest current model-to-total difference.` : "Compare every total with the FTT projection."; } const pick = winner(game); return `${pick?.name ?? game.home.name} carries the strongest straight-up model probability on the slate.`; }
function buildFaqs(week: number, mode: Mode) { return [{ question: `What are the best NFL Week ${week} ${mode === "ats" ? "picks against the spread" : mode === "totals" ? "over/under picks" : "predictions"}?`, answer: "The page ranks the current model differences and shows the evidence for every game. A larger difference is a stronger model signal, not a guaranteed result." }, { question: "Where do the odds and lines come from?", answer: "FTT reads the nflverse schedule release, stores the market snapshot time, and freezes each pregame record at kickoff. It does not scrape or name an individual sportsbook." }, { question: "How does the FTT NFL model work?", answer: "The model blends opponent-adjusted scoring margin, recent points scored and allowed, prior-season strength, home field and rest. Market lines are shown for comparison, not used to create the team rating." }, { question: "Do the picks update after kickoff?", answer: "No. Pregame projections and the attached line snapshot freeze at kickoff. Final scores then grade the archived call without rewriting it." }]; }
function buildSchema(path: string, title: string, week: number, games: ReturnType<typeof getPredictionGamesForWeek>, faqs: ReturnType<typeof buildFaqs>) { return [{ "@context": "https://schema.org", "@type": "CollectionPage", name: `${title} (2026)`, url: `${SITE_URL}${path}`, dateModified: predictionUpdatedAt(), mainEntity: { "@type": "ItemList", numberOfItems: games.length, itemListElement: games.map((game, index) => ({ "@type": "ListItem", position: index + 1, name: `${game.away.name} at ${game.home.name} Week ${week} prediction`, url: `${SITE_URL}${predictionGamePath(week, game.slug)}` })) } }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }]; }
