import Link from "next/link";
import AnalyticsPageView from "./AnalyticsPageView";
import BettingDisclosure from "./BettingDisclosure";
import JsonLd from "./JsonLd";
import TeamLogo from "./TeamLogo";
import { confidenceWeekPath, formatAmericanOdds, formatProbability, formatSpread, getPredictionGamesForWeek, moneylinePick, predictionGamePath, predictionHubPath, predictionRelease, predictionUpdatedAt, projectedScore, scorePredictionsWeekPath, straightUpWeekPath, survivorWeekPath, winner } from "../lib/nfl-predictions";
import { formatGameDate, formatGameTime } from "../lib/team-data";

const SITE_URL = "https://fantasytradetarget.com";
export type NflPoolMode = "straight" | "scores" | "survivor" | "confidence";

const config = {
  straight: { title: "NFL Week {week} Straight-Up Picks", accent: "#8bcfff", eyebrow: "Win probabilities", event: "nfl_straight_up_picks_viewed" },
  scores: { title: "NFL Week {week} Score Predictions", accent: "#dfff4f", eyebrow: "Projected final scores", event: "nfl_score_predictions_viewed" },
  survivor: { title: "NFL Week {week} Survivor Picks", accent: "#ffb29a", eyebrow: "Survivor pool board", event: "nfl_survivor_picks_viewed" },
  confidence: { title: "NFL Week {week} Confidence Pool Picks", accent: "#e7d7ff", eyebrow: "Confidence points", event: "nfl_confidence_pool_picks_viewed" },
} as const;

export default function NflPoolWeekPage({ week, mode }: { week: number; mode: NflPoolMode }) {
  const games = getPredictionGamesForWeek(week);
  const eligible = games.filter((game) => game.snapshot.status === "pregame" && winner(game));
  const ordered = mode === "scores" ? games : [...eligible].sort((left, right) => pickProbability(right) - pickProbability(left));
  const page = config[mode];
  const title = page.title.replace("{week}", String(week));
  const path = modePath(mode, week);
  const top = mode === "scores" ? [...eligible].sort((left, right) => pickProbability(right) - pickProbability(left))[0] : ordered[0];
  const topPick = top ? winner(top) : null;
  const faqs = buildFaqs(week, mode);

  return <>
    <AnalyticsPageView eventName={page.event} properties={{ week, game_count: games.length, ranked_count: eligible.length, release_id: predictionRelease.releaseId }} />
    <JsonLd data={buildSchema(path, title, week, ordered, faqs)} />
    <nav className="page-wrap flex flex-wrap gap-2 py-4 font-mono text-[10px] font-bold uppercase tracking-[0.08em] text-[#69706c]" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href={predictionHubPath()}>NFL picks</Link><span>/</span><span className="text-[#171c19]">{page.eyebrow}</span></nav>
    <section className="border-y border-[#171c19]" style={{ backgroundColor: page.accent }}><div className="page-wrap py-14 sm:py-20"><span className="eyebrow bg-white">2026 NFL · Week {week} · {page.eyebrow}</span><h1 className="mt-7 max-w-6xl text-[clamp(3rem,7vw,6.8rem)] font-black uppercase leading-[0.84] tracking-[-0.075em]">{title}<span className="text-[#8c2f14]">.</span></h1><p className="mt-8 max-w-4xl border-l-4 border-[#171c19] pl-5 text-lg font-black leading-8">{heroAnswer(mode, top, topPick, eligible.length)}</p><p className="mt-5 max-w-3xl text-sm leading-7 text-[#4f5551]">Updated {formatUpdated(predictionUpdatedAt())}. Projections refresh before kickoff, then the archived call stays fixed.</p></div></section>
    <section className="page-wrap py-12"><div className="mb-7 flex flex-wrap gap-3"><Link className={pill(mode === "straight")} href={straightUpWeekPath(week)}>Straight up</Link><Link className={pill(mode === "scores")} href={scorePredictionsWeekPath(week)}>Scores</Link><Link className={pill(mode === "survivor")} href={survivorWeekPath(week)}>Survivor</Link><Link className={pill(mode === "confidence")} href={confidenceWeekPath(week)}>Confidence pool</Link></div>{mode === "scores" ? <ScoreBoard games={ordered} /> : <PickBoard games={ordered} mode={mode} />}</section>
    <section className="border-y border-[#171c19] bg-[#171c19] text-white"><div className="page-wrap grid gap-8 py-12 lg:grid-cols-[0.8fr_1.2fr]"><div><span className="eyebrow bg-[#dfff4f] text-[#171c19]">How to use it</span><h2 className="section-title mt-6">{usageHeading(mode)}</h2></div><div className="space-y-4 text-sm leading-7 text-white/70">{usageCopy(mode)}<p>The model uses only information available before the target week: opponent-adjusted team strength, scoring form, prior-season strength, home field and rest. Market odds are shown for context and do not create the team rating.</p><Link href="/methodology#nfl-predictions" className="inline-block font-mono text-[10px] font-black uppercase text-[#dfff4f] underline">Read the methodology →</Link></div></div></section>
    <section className="page-wrap py-12"><span className="eyebrow">Questions, answered</span><div className="mt-7 grid gap-px border border-[#171c19] bg-[#171c19] lg:grid-cols-2">{faqs.map(({ question, answer }) => <article key={question} className="bg-[#f3f0e7] p-6"><h2 className="text-xl font-black tracking-[-0.03em]">{question}</h2><p className="mt-3 text-sm leading-7 text-[#69706c]">{answer}</p></article>)}</div></section>
    <BettingDisclosure />
  </>;
}

function PickBoard({ games, mode }: { games: ReturnType<typeof getPredictionGamesForWeek>; mode: Exclude<NflPoolMode, "scores"> }) {
  return <div className="overflow-x-auto border border-[#171c19] bg-white shadow-[6px_6px_0_#171c19]"><table className="w-full min-w-[880px] text-left text-sm"><thead className="bg-[#171c19] font-mono text-[10px] uppercase tracking-[0.08em] text-white"><tr><th className="p-4">{mode === "confidence" ? "Points" : "Rank"}</th><th className="p-4">Pick</th><th className="p-4">Opponent</th><th className="p-4">FTT win chance</th><th className="p-4">Market</th><th className="p-4">Projected score</th><th className="p-4">Read</th></tr></thead><tbody className="divide-y divide-[#bcb9ae]">{games.map((game, index) => { const pick = winner(game)!; const moneyline = moneylinePick(game); const score = projectedScore(game); const opponent = pick.abbr === game.home.abbr ? game.away : game.home; const points = games.length - index; return <tr key={game.snapshot.gameId} className={index < 3 ? "bg-[#f7ffd2]" : "bg-white"}><td className="p-4 text-2xl font-black">{mode === "confidence" ? points : index + 1}</td><td className="p-4"><div className="flex items-center gap-3"><TeamLogo team={pick.abbr} size={40} decorative /><strong>{pick.name}</strong></div></td><td className="p-4">vs. {opponent.nickname}</td><td className="p-4 font-black text-[#174f35]">{formatProbability(moneyline?.probability)}</td><td className="p-4">{formatAmericanOdds(moneyline?.odds ?? null)}</td><td className="p-4">{score ? `${game.away.abbr} ${score.away}, ${game.home.abbr} ${score.home}` : "—"}</td><td className="p-4"><Link href={predictionGamePath(game.snapshot.week, game.slug)} className="font-mono text-[10px] font-black uppercase underline">Game file →</Link></td></tr>; })}</tbody></table></div>;
}

function ScoreBoard({ games }: { games: ReturnType<typeof getPredictionGamesForWeek> }) {
  return <div className="grid gap-5 xl:grid-cols-2">{games.map((game) => { const score = projectedScore(game); const pick = winner(game); return <article key={game.snapshot.gameId} className="border border-[#171c19] bg-white p-6 shadow-[5px_5px_0_#171c19]"><div className="flex items-center justify-between gap-4"><TeamBlock team={game.away} score={score?.away} /><span className="font-mono text-[10px] font-black uppercase text-[#69706c]">at</span><TeamBlock team={game.home} score={score?.home} reverse /></div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-[#bcb9ae] pt-4"><p className="text-xs leading-6 text-[#69706c]">{game.homeGame.weekday}, {formatGameDate(game.homeGame.date)} · {formatGameTime(game.homeGame.time)} · projected total {game.snapshot.modelTotal?.toFixed(1) ?? "—"} · listed total {game.snapshot.market.totalLine ?? "—"}</p><Link href={predictionGamePath(game.snapshot.week, game.slug)} className="font-mono text-[10px] font-black uppercase underline">{pick ? `${pick.nickname} game file` : "Game file"} →</Link></div></article>; })}</div>;
}

function TeamBlock({ team, score, reverse = false }: { team: ReturnType<typeof getPredictionGamesForWeek>[number]["home"]; score?: number; reverse?: boolean }) { return <div className={`flex min-w-0 items-center gap-3 ${reverse ? "flex-row-reverse text-right" : ""}`}><TeamLogo team={team.abbr} size={52} decorative /><div><span className="font-mono text-[9px] font-black uppercase text-[#69706c]">{team.abbr}</span><strong className="block truncate text-lg">{team.nickname}</strong></div><span className="text-4xl font-black">{score ?? "—"}</span></div>; }
function pickProbability(game: ReturnType<typeof getPredictionGamesForWeek>[number]) { return moneylinePick(game)?.probability ?? 0; }
function modePath(mode: NflPoolMode, week: number) { return mode === "straight" ? straightUpWeekPath(week) : mode === "scores" ? scorePredictionsWeekPath(week) : mode === "survivor" ? survivorWeekPath(week) : confidenceWeekPath(week); }
function pill(active: boolean) { return `border border-[#171c19] px-4 py-3 font-mono text-[10px] font-black uppercase shadow-[3px_3px_0_#171c19] ${active ? "bg-[#171c19] text-white" : "bg-white"}`; }
function formatUpdated(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit", timeZone: "America/New_York", timeZoneName: "short" }).format(new Date(value)); }
function heroAnswer(mode: NflPoolMode, game: ReturnType<typeof getPredictionGamesForWeek>[number] | undefined, pick: ReturnType<typeof winner>, count: number) { if (!game || !pick) return "The board will populate when the week’s schedule is available."; const probability = formatProbability(moneylinePick(game)?.probability); if (mode === "scores") { const score = projectedScore(game); return `${pick.name} leads the strongest projected result on a ${count}-game board${score ? `, with ${game.away.abbr} ${score.away} and ${game.home.abbr} ${score.home}` : ""}.`; } if (mode === "survivor") return `${pick.name} is the top available survivor candidate at ${probability} model win probability. Check your pool history before choosing: a team can usually be used only once.`; if (mode === "confidence") return `${pick.name} gets the highest confidence assignment at ${probability}. Point values descend across the full slate.`; return `${pick.name} is the strongest straight-up pick at ${probability}, followed by the rest of the slate in probability order.`; }
function usageHeading(mode: NflPoolMode) { return mode === "survivor" ? "Survive the week without forgetting the season." : mode === "confidence" ? "Convert probabilities into pool points." : mode === "scores" ? "Use the score, then inspect the assumptions." : "Rank the slate by win probability."; }
function usageCopy(mode: NflPoolMode) { if (mode === "survivor") return <><p>Start with the highest win probabilities, remove any team you have already used, then consider whether saving a heavy favorite creates more value in a later week. The board ranks this week only; it does not know your pool history.</p><p>A favorite is not safe. One upset ends most survivor entries, so the probability is a decision input—not a guarantee.</p></>; if (mode === "confidence") return <><p>The strongest pick receives the maximum points and every following game receives one fewer point. If your pool uses a different scale, preserve the order and remap the points.</p><p>Close probabilities are effectively ties. Use your pool&apos;s tiebreak rule instead of forcing certainty the model does not have.</p></>; if (mode === "scores") return <><p>Projected totals come from each team&apos;s scoring and defensive profile, regressed toward the previous season. The projected margin then splits that total into two team scores.</p><p>Exact scores are best read as a compact description of pace and expected margin, not a claim that the game will land on a precise number.</p></>; return <><p>The table orders every pick by the model&apos;s estimated chance to win, independent of the point spread. Moneylines are displayed as market context.</p><p>Use the probability gap to separate clear favorites from toss-ups. A 52% pick and a 51% pick should not be treated as meaningfully different.</p></>; }
function buildFaqs(week: number, mode: NflPoolMode) { const label = mode === "scores" ? "score predictions" : mode === "survivor" ? "survivor picks" : mode === "confidence" ? "confidence pool picks" : "straight-up picks"; return [{ question: `What are the NFL Week ${week} ${label}?`, answer: "FTT ranks the complete weekly slate from a pregame team-strength model and links every answer to its matchup evidence." }, { question: "When do these NFL picks update?", answer: "The board refreshes with the scheduled data release before kickoff. Each game prediction freezes when that game starts." }, { question: "Does the model use the betting line to make its pick?", answer: "No. Team strength, scoring, site and rest create the prediction. The timestamped market line is shown separately for comparison." }, { question: mode === "survivor" ? "Does FTT know which survivor teams I already used?" : "Are these guaranteed picks?", answer: mode === "survivor" ? "No. Remove teams already used in your own pool before choosing from the ranked board." : "No. Probabilities and score projections describe uncertainty; they do not guarantee an outcome or profit." }]; }
function buildSchema(path: string, title: string, week: number, games: ReturnType<typeof getPredictionGamesForWeek>, faqs: ReturnType<typeof buildFaqs>) { return [{ "@context": "https://schema.org", "@type": "CollectionPage", name: `${title} (2026)`, url: `${SITE_URL}${path}`, dateModified: predictionUpdatedAt(), mainEntity: { "@type": "ItemList", numberOfItems: games.length, itemListElement: games.map((game, index) => ({ "@type": "ListItem", position: index + 1, name: `${game.away.name} at ${game.home.name}`, url: `${SITE_URL}${predictionGamePath(week, game.slug)}` })) } }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }]; }
