name: Fast production deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      ref: main
    secrets: inherit
